/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Aplikasi;

import java.io.File;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JRViewer;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author ACER
 */
public class utama extends javax.swing.JFrame {
 private Connection conec;
    private JasperDesign Jasper_Design;
    private JasperReport Jasper_Report;
    private Map<String, Object> Parameter = new HashMap<String, Object>();
    private JasperPrint Jasper_Print;
    /**
     * Creates new form utama
     */
    JFrame frame = new JFrame();
    public utama() {
        initComponents();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH); 
        koneksiDatabase();
    }
    
    private void koneksiDatabase() {
        try {
            Class.forName("com.mysql.jdbc.Driver");
        }
        catch(ClassNotFoundException cnf){}
        try {conec = DriverManager.getConnection("jdbc:mysql://localhost/db_koperasi","root","");
        System.out.println("Koneksi Sukses");
                }
        catch(SQLException se){
            System.out.println("Koneksi Gagal : "+se);
        }
        catch(Exception e){}
    }

//    public class fungsiCetak {
//    public fungsiCetak(String namareport){
//        try{
//            File report_file = new File(namareport);
////            Jasper_Report = (JasperReport) JRLoader.loadObject(report_file.getPath());
//            Jasper_Report = JasperCompileManager.compileReport(report_file.getPath());
//            Jasper_Print = JasperFillManager.fillReport(Jasper_Report, null, conec);
//            JasperViewer.viewReport(Jasper_Print,false);
//        }
//        catch(Exception e){
//            System.out.print(e.getMessage());
//        }
//    }
//}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jOptionPane1 = new javax.swing.JOptionPane();
        canvas1 = new java.awt.Canvas();
        jMenuItem1 = new javax.swing.JMenuItem();
        jLabel1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mst_anggota = new javax.swing.JMenuItem();
        mst_rekening = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        trs_simpanan = new javax.swing.JMenuItem();
        trs_pinjaman = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        lpr_simpanan = new javax.swing.JMenuItem();
        lpr_pinjaman = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel1.setText("PT. SARICOCO TRI TUNGGAL MANDIRI");

        jButton6.setText("Keluar");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setText("Sistem Informasi Koperasi \"TUNAS KELAPA\"");

        jLabel3.setIcon(new javax.swing.ImageIcon("E:\\SKRIPSI KOPERASI\\KOPERASI\\koperasi\\src\\Aplikasi\\Saving-Bonds-500x383.jpg")); // NOI18N

        jMenu1.setText("Master");

        mst_anggota.setText("Anggota");
        mst_anggota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mst_anggotaActionPerformed(evt);
            }
        });
        jMenu1.add(mst_anggota);

        mst_rekening.setText("Rekening nasabah");
        mst_rekening.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mst_rekeningActionPerformed(evt);
            }
        });
        jMenu1.add(mst_rekening);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Transaksi");

        trs_simpanan.setText("Simpanan");
        trs_simpanan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                trs_simpananActionPerformed(evt);
            }
        });
        jMenu2.add(trs_simpanan);

        trs_pinjaman.setText("Pinjaman");
        trs_pinjaman.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                trs_pinjamanActionPerformed(evt);
            }
        });
        jMenu2.add(trs_pinjaman);

        jMenuBar1.add(jMenu2);

        jMenu5.setText("Laporan");

        lpr_simpanan.setText("Laporan Pinjaman");
        lpr_simpanan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lpr_simpananActionPerformed(evt);
            }
        });
        jMenu5.add(lpr_simpanan);

        lpr_pinjaman.setText("Laporan Simpanan");
        lpr_pinjaman.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lpr_pinjamanActionPerformed(evt);
            }
        });
        jMenu5.add(lpr_pinjaman);

        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(560, 560, 560)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 152, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 537, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46)))
                .addComponent(jLabel12)
                .addGap(1, 1, 1))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(37, 37, 37)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 477, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(jLabel8)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addComponent(jButton6)
                .addGap(342, 342, 342))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mst_rekeningActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mst_rekeningActionPerformed
        // TODO add your handling code here:
        new rekening_nasabah().setVisible(true);
         //dispose();
    }//GEN-LAST:event_mst_rekeningActionPerformed

    private void mst_anggotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mst_anggotaActionPerformed
        // TODO add your handling code here:
        new anggota().setVisible(true);
         //dispose();
    }//GEN-LAST:event_mst_anggotaActionPerformed

    private void trs_simpananActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_trs_simpananActionPerformed
        // TODO add your handling code here:
        new trans_simpanan().show();
        //dispose();
    }//GEN-LAST:event_trs_simpananActionPerformed

    private void trs_pinjamanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_trs_pinjamanActionPerformed
        // TODO add your handling code here:
        new trans_pinjaman().show();
        //dispose(
    }//GEN-LAST:event_trs_pinjamanActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        new login_koperasi().setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_formWindowOpened

    private void lpr_simpananActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lpr_simpananActionPerformed
        // TODO add your handling code here:
       try{
           String report="src/report/laporantranspinjam.jrxml";
           HashMap hash = new HashMap();
           File file = new File(report);
            Jasper_Design = JRXmlLoader.load(file);

            Jasper_Report = JasperCompileManager.compileReport(Jasper_Design);
            Jasper_Print = JasperFillManager.fillReport(Jasper_Report, null, conec);
            JasperViewer.viewReport(Jasper_Print,false);
        }
        catch(Exception e){
            System.out.print(e.getMessage());
        }
    }//GEN-LAST:event_lpr_simpananActionPerformed

    private void lpr_pinjamanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lpr_pinjamanActionPerformed
        // TODO add your handling code here:
        try{
           String report="src/report/laporantranssimpan.jrxml";
           HashMap hash = new HashMap();
           File file = new File(report);
            Jasper_Design = JRXmlLoader.load(file);

            Jasper_Report = JasperCompileManager.compileReport(Jasper_Design);
            Jasper_Print = JasperFillManager.fillReport(Jasper_Report, null, conec);
            JasperViewer.viewReport(Jasper_Print,false);
        }
        catch(Exception e){
            System.out.print(e.getMessage());
        }
    }//GEN-LAST:event_lpr_pinjamanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new utama().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Canvas canvas1;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JOptionPane jOptionPane1;
    private javax.swing.JMenuItem lpr_pinjaman;
    private javax.swing.JMenuItem lpr_simpanan;
    private javax.swing.JMenuItem mst_anggota;
    private javax.swing.JMenuItem mst_rekening;
    private javax.swing.JMenuItem trs_pinjaman;
    private javax.swing.JMenuItem trs_simpanan;
    // End of variables declaration//GEN-END:variables
}
